import { isTouch } from './utils';

const levelData = [
	{
		index: 0,
		id: 'tutorial1',
		title: '#0.1',
		revealed: 'Solved!',
		stacks: {
			xStack: [[1], [1], [1], [1], [1]],
			yStack: [[5]],
		},
		cords: { x: 5, y: 1 },
		aparatasInit: {
			type: 'tut',
			text: `Hello and welcome to Crosseris! A japanese Nanogram game named after inventor Non Ishida. 
      Game principle is simple - cells in a grid must be colored or left blank to corresponding sets of numbers at the side of the grid.`,
		},
		waterMark: null,
	},
	{
		index: 1,
		id: 'tutorial2',
		title: '#0.2',
		revealed: 'Solved!',
		stacks: {
			xStack: [[2], [2], [2], [2], [2]],
			yStack: [[5], [5]],
		},
		cords: { x: 5, y: 2 },
		aparatasInit: {
			type: 'tut',
			text: `${
				isTouch ? 'Tap' : 'Click'
			} and drag accros row or column to color multiple cells.`,
		},
		waterMark: null,
	},
	{
		index: 2,
		id: 'tutorial3',
		title: '#0.3',
		revealed: 'Solved!',
		stacks: {
			xStack: [[1], [1], [0], [1], [1]],
			yStack: [[2, 2]],
		},
		cords: { x: 5, y: 1 },
		aparatasInit: {
			type: 'tut',
			text:
				'Sets of colored cells must be separated with atleast one empty cell.',
		},
		waterMark: null,
	},

	{
		index: 3,
		id: 'tutorial4',
		title: '#0.4',
		revealed: 'Solved!',
		stacks: {
			xStack: [[3], [4], [5], [4], [3]],
			yStack: [[3], [5], [5], [5], [1]],
		},
		cords: { x: 5, y: 5 },
		aparatasInit: {
			type: 'tut',
			text: `${
				isTouch ? 'Tap' : 'Click'
			} on a cell twice to mark it with a cross. Crossed cells are used as indicators of which cells should definately be left blank! `,
		},
		waterMark: null,
	},
	{
		index: 4,
		id: 'SHOSHINSHA1',
		title: '#1.1',
		revealed: 'House',
		stacks: {
			xStack: [[3], [4], [3, 1], [4], [3]],
			yStack: [[1], [3], [5], [2, 2], [5]],
		},
		cords: { x: 5, y: 5 },
		aparatasInit: { type: null },
		waterMark: 'bird',
	},
	{
		index: 5,
		id: 'SHOSHINSHA2',
		title: '#1.2',
		revealed: 'Heart',
		stacks: {
			xStack: [[2], [4], [4], [4], [2]],
			yStack: [[1, 1], [5], [5], [3], [1]],
		},
		cords: { x: 5, y: 5 },
		aparatasInit: { type: null },
		waterMark: 'bird',
	},
	{
		index: 6,
		id: 'SHOSHINSHA3',
		title: '#1.3',
		revealed: 'Rocket',
		stacks: {
			xStack: [[2], [3], [2, 2], [3], [2]],
			yStack: [[1], [3], [1, 1], [5], [1, 1, 1]],
		},
		cords: { x: 5, y: 5 },
		aparatasInit: { type: null },
		waterMark: 'bird',
	},
	{
		index: 7,
		id: 'SHOSHINSHA4',
		title: '#1.4',
		revealed: 'Flower',
		stacks: {
			xStack: [[3, 1], [3, 1], [7], [3, 1], [3, 1]],
			yStack: [[1, 1, 1], [5], [5], [3], [1], [1, 1, 1], [3]],
		},
		cords: { x: 5, y: 7 },
		aparatasInit: { type: null },
		waterMark: 'bird',
	},
	{
		index: 8,
		id: 'RUKI1',
		title: '#2.1',
		revealed: 'Umbrella',
		stacks: {
			xStack: [[1], [2], [2, 1], [7], [2], [2], [1]],
			yStack: [[1], [5], [7], [1], [1], [1], [2]],
		},
		cords: { x: 7, y: 7 },
		aparatasInit: { type: null },
		waterMark: 'koi',
	},
	{
		index: 9,
		id: 'RUKI2',
		title: '#2.2',
		revealed: 'Ying Yang',
		stacks: {
			xStack: [[3], [5], [2, 4], [4, 1], [1, 1, 1], [1, 1], [3]],
			yStack: [[3], [3, 1], [2, 1, 1], [4, 1], [3, 1, 1], [2, 1], [3]],
		},
		cords: { x: 7, y: 7 },
		aparatasInit: { type: null },
		waterMark: 'koi',
	},
	{
		index: 10,
		id: 'RUKI3',
		title: '#2.3',
		revealed: 'Camera',
		stacks: {
			xStack: [
				[7],
				[2, 5],
				[1, 5],
				[4, 2],
				[1, 1, 2, 1],
				[3, 1, 2, 1],
				[1, 4, 2],
				[1, 7],
				[4, 5],
				[7],
			],
			yStack: [
				[4],
				[1, 1],
				[1, 4, 1],
				[4, 4],
				[1, 5, 1],
				[4, 4],
				[3, 2, 3],
				[3, 2, 3],
				[4, 4],
				[10],
			],
		},
		cords: { x: 10, y: 10 },
		aparatasInit: { type: null },
		waterMark: 'koi',
	},
	{
		index: 11,
		id: 'RUKI4',
		title: '#2.4',
		revealed: 'Fish',
		stacks: {
			xStack: [
				[2],
				[5],
				[2, 3],
				[5, 1],
				[4, 3],
				[10],
				[8, 1],
				[1, 5, 1],
				[1, 3],
				[6],
			],
			yStack: [
				[4],
				[3],
				[5],
				[7, 1],
				[1, 7],
				[2, 1, 5],
				[4, 5],
				[2, 4, 1],
				[4, 1],
				[4],
			],
		},
		cords: { x: 10, y: 10 },
		aparatasInit: { type: null },
		waterMark: 'koi',
	},
	{
		index: 12,
		id: 'SAINO1',
		title: '#3.1',
		revealed: 'Ship',
		stacks: {
			xStack: [
				[1],
				[2, 1],
				[3, 2],
				[5, 2],
				[7, 2],
				[3],
				[5, 2],
				[3, 2],
				[2, 1],
				[1],
			],
			yStack: [[1], [1], [2, 1], [2, 1], [3, 2], [4, 3], [5, 4], [1], [8], [6]],
		},
		cords: { x: 10, y: 10 },
		aparatasInit: { type: null },
		waterMark: 'dragon',
	},
];

export default levelData;
