// field
export const SET_FIELD = 'SET_FIELD';
export const SET_IS_FIELD_ACTIVE = 'SET_IS_FIELD_ACTIVE';
export const SET_APARATAS_ACTIVE = 'SET_APARATAS_ACTIVE';
export const SET_IS_WINNER = 'SET_IS_WINNER';
export const SET_BLOCK = 'SET_BLOCK';
export const SET_PLAY_STACK = 'SET_PLAY_STACK';
export const SET_BLOCK_SIZE = 'SET_BLOCK_SIZE';
export const STOP_MULTI_SELECT = 'STOP_MULTI_SELECT';
export const MULTI_SELECT_TRIG = 'MULTI_SELECT_TRIG';
export const MULTI_SELECT_APPLY = 'MULTI_SELECT_APPLY';
export const UN_DO = 'UN_DO';
export const ZOOM = 'ZOOM';
export const SET_MODE = 'SET_MODE';
export const DEV_FIELD_SIZE_SET = 'DEV_FIELD_SIZE_SET';
export const DEV_SET_TITLES = 'DEV_SET_TITLES';
export const PLAY_LEVEL_INIT = 'PLAY_LEVEL_INIT';

// lvlDataStore
export const STORE_CUSTOM_LEVELS = 'STORE_CUSTOM_LEVELS';
export const STORE_ORIGINAL_LEVELS = 'STORE_ORIGINAL_LEVELS';
export const SET_ORIGINAL_OR_CUSTOM_LVL_DATA_SOURCE =
	'SET_ORIGINAL_OR_CUSTOM_LVL_DATA_SOURCE';
